params:
  seed: 42

  algo:
    name: sac

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:
    mlp:
      units: [512, 256, 128]
      activation: elu
      initializer:
        name: default
    log_std_bounds: [-5, 2]

  env:
    clip_observations: 5.0
    clip_actions: 1.0

  load_checkpoint: False
  load_path: ''

  config:
    name: table_tennis_sac
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: False
    mixed_precision: False
    normalize_input: True
    num_actors: -1
    reward_shaper:
      scale_value: 1.0
    gamma: 0.98
    critic_tau: 0.005
    batch_size: 4096
    init_alpha: 0.02
    learnable_temperature: False
    replay_buffer_size: 1000000
    actor_lr: 3.0e-4
    critic_lr: 3.0e-4
    alpha_lr: 5.0e-5
    max_epochs: 50000
    num_steps_per_episode: 8
    num_warmup_steps: 100
    save_best_after: 500
    save_frequency: 1000
    target_entropy_coef: 0.5
    env_config: {}
